import React, { useMemo, useState } from "react";
import { motion } from "framer-motion";
import JSZip from "jszip";
import {
  Download,
  ArrowRight,
  Sparkles,
  Code2,
  Eye,
  Package,
  Send,
} from "lucide-react";
import { brands } from "./brand-tokens.js";
import { modules, modulesByCategory } from "./catalog.js";

// ─────────────────────────────────────────────────────────────────────────────
// nott — Easy modules for every SI project
// Version: 2026-06-06 (v8)
//
// v7 → v8 변경점 (브랜드 로고 락업):
//  - 단색 칩 → [브랜드색 모노그램] + 워드마크 형태의 로고 락업으로 다듬음
//  - 앱 프리뷰(BrandMark)와 생성 starter 헤더에 동일 적용 (상표 리스크 없는 안전 방식)
//  - company.logoSvg 들어오면 락업 대신 실제 로고 SVG 렌더 (drop-in)
//
// (이전) v6 → v7: chat 모듈 대화형 프리뷰 + 작동하는 채팅 starter
// ─────────────────────────────────────────────────────────────────────────────

function NottLogo({ height = 26 }) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 17 132.73 30.29"
      height={height}
      role="img"
      aria-label="nott"
    >
      <rect fill="#ff595f" y="29.94" width="12.94" height="17.35" />
      <polygon fill="#ff595f" points="30.83 17 30.83 47.29 17.89 47.29 17.89 29.94 12.94 29.94 12.94 17 30.83 17" />
      <path fill="#02aa5e" d="M34.94,17v30.29h29.55v-30.29h-29.55ZM52.48,35.03h-5.54v-5.78h5.54v5.78Z" />
      <polygon fill="#ffc82b" points="99.01 17 99.01 29.94 90.33 29.94 90.33 47.29 77.4 47.29 77.4 29.94 68.72 29.94 68.72 17 99.01 17" />
      <polygon fill="#0a62bb" points="132.73 17 132.73 29.94 124.05 29.94 124.05 47.29 111.11 47.29 111.11 29.94 102.43 29.94 102.43 17 132.73 17" />
    </svg>
  );
}

function NottSymbol({ size = 18 }) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="252 0 65.04 64.29"
      width={size}
      height={size}
      role="img"
      aria-label="nott symbol"
    >
      <rect fill="#ff595f" x="252.54" y="12.94" width="12.94" height="17.35" />
      <polygon fill="#ff595f" points="283.37 0 283.37 30.29 270.43 30.29 270.43 12.94 265.48 12.94 265.48 0 283.37 0" />
      <path fill="#02aa5e" d="M287.49,0v30.29h29.55V0h-29.55ZM305.03,18.03h-5.54v-5.78h5.54v5.78Z" />
      <polygon fill="#ffc82b" points="283.32 34 283.32 46.94 274.64 46.94 274.64 64.29 261.7 64.29 261.7 46.94 253.03 46.94 253.03 34 283.32 34" />
      <polygon fill="#0a62bb" points="317.04 34 317.04 46.94 308.36 46.94 308.36 64.29 295.42 64.29 295.42 46.94 286.74 46.94 286.74 34 317.04 34" />
    </svg>
  );
}

// ── source generation ────────────────────────────────────────────────────────

// Short monogram for the logo lockup (latin wordmark → 1–2 letters).
function markOf(company) {
  return company.logoText.length <= 2 ? company.logoText : company.logoText[0];
}

function brandBlock(company, mod) {
  return `// Brand tokens generated from nott's brand-token system (src/brand-tokens.js).
// Theming is driven by CSS variables — swap these to re-skin for any client.
const brand = {
  name: "${company.name}",
  logoText: "${company.logoText}",
  mark: "${markOf(company)}",
  module: { name: "${mod.name}", tagline: "${mod.tagline}" },
  tokens: ${JSON.stringify(company.tokens)},
};

const cssVars = {
  "--brand-primary": brand.tokens.primary,
  "--brand-on-primary": brand.tokens.onPrimary,
  "--brand-surface": brand.tokens.surface,
  "--brand-on-surface": brand.tokens.onSurface,
};

// Brand logo lockup: monogram tile + wordmark, themed via CSS vars.
function BrandMark() {
  return (
    <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
      <span style={{ display: "inline-flex", width: 24, height: 24, alignItems: "center", justifyContent: "center", borderRadius: 6, background: "var(--brand-primary)", color: "var(--brand-on-primary)", fontWeight: 700, fontSize: 11, letterSpacing: "-0.02em" }}>{brand.mark}</span>
      <span style={{ color: "var(--brand-primary)", fontWeight: 700, fontSize: 16, letterSpacing: "-0.01em" }}>{brand.logoText}</span>
    </div>
  );
}`;
}

function componentNameOf(mod) {
  return mod.id.charAt(0).toUpperCase() + mod.id.slice(1) + "Preview";
}

// Request-body shape per chat module (matches each module's API contract).
function chatBodyExpr(mod) {
  if (mod.id === "slm") return "{ prompt: text }";
  if (mod.id === "rag") return "{ query: text, topK: 5 }";
  return '{ messages: [{ role: "user", content: text }] }';
}

function makeChatSource(company, mod) {
  const componentName = componentNameOf(mod);
  return `// Generated by nott — Easy modules for every SI project
// Package : ${mod.pkg}
// Client  : ${company.name} (${company.logoText})
// Module  : ${mod.name} (${mod.tagline})
// Endpoint: ${mod.endpoint}

import React from "react";

const API_ENDPOINT = "${mod.endpoint}";
const GREETING = "${mod.greeting}";

${brandBlock(company, mod)}

export default function ${componentName}() {
  const [messages, setMessages] = React.useState([{ role: "assistant", text: GREETING }]);
  const [input, setInput] = React.useState("");
  const [busy, setBusy] = React.useState(false);

  const send = async () => {
    const text = input.trim();
    if (!text || busy) return;
    setMessages((m) => [...m, { role: "user", text }]);
    setInput("");
    setBusy(true);

    let reply;
    try {
      const [method, path] = API_ENDPOINT.split(" ");
      const res = await fetch(path, {
        method,
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(${chatBodyExpr(mod)})
      });
      const data = await res.json();
      reply = data.reply || data.answer || data.content || JSON.stringify(data);
    } catch (e) {
      // No backend yet → demo fallback so the starter runs out of the box.
      reply = "(데모 응답) \\u201C" + text + "\\u201D — " + API_ENDPOINT + " 연결 시 실제 답변이 표시됩니다.";
    }
    setMessages((m) => [...m, { role: "assistant", text: reply }]);
    setBusy(false);
  };

  return (
    <main style={{ ...cssVars, minHeight: "100vh", background: "var(--brand-surface)", color: "var(--brand-on-surface)", padding: 32 }}>
      <section style={{ maxWidth: 560, margin: "0 auto", background: "white", borderRadius: 16, padding: 20, display: "flex", flexDirection: "column", height: 560 }}>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
          <BrandMark />
          <div style={{ fontSize: 11, color: "#94a3b8" }}>powered by nott</div>
        </div>
        <h1 style={{ fontSize: 20, marginTop: 12, fontWeight: 600 }}>{brand.module.name}</h1>
        <p style={{ fontSize: 12, color: "var(--brand-primary)", marginTop: 2, fontWeight: 600 }}>{brand.module.tagline}</p>

        <div style={{ flex: 1, overflowY: "auto", marginTop: 14, display: "flex", flexDirection: "column", gap: 8 }}>
          {messages.map((m, i) => (
            <div key={i} style={{ alignSelf: m.role === "user" ? "flex-end" : "flex-start", maxWidth: "85%" }}>
              <div style={{
                borderRadius: 12,
                padding: "8px 11px",
                fontSize: 13,
                lineHeight: 1.5,
                background: m.role === "user" ? "var(--brand-primary)" : "#f1f5f9",
                color: m.role === "user" ? "var(--brand-on-primary)" : "#0f172a"
              }}>
                {m.text}
              </div>
            </div>
          ))}
        </div>

        <div style={{ display: "flex", gap: 8, marginTop: 12 }}>
          <input
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={(e) => e.key === "Enter" && send()}
            placeholder="메시지를 입력하세요…"
            style={{ flex: 1, border: "1px solid #e2e8f0", borderRadius: 10, padding: "10px 12px", fontSize: 13, outlineColor: "var(--brand-primary)" }}
          />
          <button onClick={send} disabled={busy} style={{ background: "var(--brand-primary)", color: "var(--brand-on-primary)", border: 0, borderRadius: 10, padding: "0 16px", fontWeight: 600, fontSize: 13, cursor: "pointer", opacity: busy ? 0.6 : 1 }}>
            전송
          </button>
        </div>
      </section>
    </main>
  );
}
`;
}

function makeApiSource(company, mod) {
  const componentName = componentNameOf(mod);
  return `// Generated by nott — Easy modules for every SI project
// Package : ${mod.pkg}
// Client  : ${company.name} (${company.logoText})
// Module  : ${mod.name} (${mod.tagline})
// Endpoint: ${mod.endpoint}

import React from "react";

const API_ENDPOINT = "${mod.endpoint}";

${brandBlock(company, mod)}

export default function ${componentName}() {
  const callApi = async () => {
    const [method, path] = API_ENDPOINT.split(" ");
    const res = await fetch(path, {
      method,
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(${JSON.stringify(mod.sample)})
    });
    return res.json();
  };

  return (
    <main style={{ ...cssVars, minHeight: "100vh", background: "var(--brand-surface)", color: "var(--brand-on-surface)", padding: 32 }}>
      <section style={{ maxWidth: 880, margin: "0 auto", background: "white", borderRadius: 16, padding: 24 }}>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
          <BrandMark />
          <div style={{ fontSize: 11, color: "#94a3b8" }}>powered by nott</div>
        </div>
        <h1 style={{ fontSize: 28, marginTop: 24, fontWeight: 600, letterSpacing: "-0.01em" }}>{brand.module.name}</h1>
        <p style={{ fontSize: 12, color: "var(--brand-primary)", marginTop: 4, fontWeight: 600 }}>{brand.module.tagline}</p>
        <p style={{ fontSize: 14, color: "#64748b", marginTop: 12, lineHeight: 1.6 }}>${mod.desc}</p>
        <div style={{ marginTop: 16, padding: 10, background: "#0f172a", color: "#e2e8f0", borderRadius: 8, fontFamily: "monospace", fontSize: 12 }}>{API_ENDPOINT}</div>
        <button onClick={callApi} style={{ marginTop: 16, background: "var(--brand-primary)", color: "var(--brand-on-primary)", border: 0, borderRadius: 999, padding: "10px 18px", fontWeight: 600, fontSize: 13, cursor: "pointer" }}>
          Start with {brand.name}
        </button>
      </section>
    </main>
  );
}
`;
}

function makeTableSource(company, mod) {
  const componentName = componentNameOf(mod);
  return `// Generated by nott — Easy modules for every SI project
// Package : ${mod.pkg}
// Client  : ${company.name} (${company.logoText})
// Module  : ${mod.name} (${mod.tagline})

import React from "react";

${brandBlock(company, mod)}

const columns = ${JSON.stringify(mod.columns)};

export default function ${componentName}() {
  const rows = [1, 2, 3].map((n) =>
    columns.map((c, i) => (i === 0 ? "#" + (1000 + n) : c + " " + n))
  );

  return (
    <main style={{ ...cssVars, minHeight: "100vh", background: "var(--brand-surface)", color: "var(--brand-on-surface)", padding: 32 }}>
      <section style={{ maxWidth: 880, margin: "0 auto", background: "white", borderRadius: 16, padding: 24 }}>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
          <BrandMark />
          <div style={{ fontSize: 11, color: "#94a3b8" }}>powered by nott</div>
        </div>
        <h1 style={{ fontSize: 24, marginTop: 20, fontWeight: 600 }}>{brand.module.name}</h1>
        <p style={{ fontSize: 12, color: "var(--brand-primary)", marginTop: 4, fontWeight: 600 }}>{brand.module.tagline}</p>
        <p style={{ fontSize: 13, color: "#64748b", marginTop: 10, lineHeight: 1.6 }}>${mod.desc}</p>
        <div style={{ marginTop: 16, overflowX: "auto" }}>
          <table style={{ width: "100%", borderCollapse: "collapse", fontSize: 13 }}>
            <thead>
              <tr>
                {columns.map((c) => (
                  <th key={c} style={{ textAlign: "left", padding: "10px 12px", borderBottom: "2px solid var(--brand-primary)", color: "var(--brand-primary)", fontSize: 12 }}>{c}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {rows.map((r, ri) => (
                <tr key={ri}>
                  {r.map((cell, ci) => (
                    <td key={ci} style={{ padding: "10px 12px", borderBottom: "1px solid #eef2f7" }}>{cell}</td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        <button style={{ marginTop: 16, background: "var(--brand-primary)", color: "var(--brand-on-primary)", border: 0, borderRadius: 10, padding: "10px 18px", fontWeight: 600, fontSize: 13, cursor: "pointer" }}>
          ${mod.cta}
        </button>
      </section>
    </main>
  );
}
`;
}

function makeFormSource(company, mod) {
  const componentName = componentNameOf(mod);
  return `// Generated by nott — Easy modules for every SI project
// Package : ${mod.pkg}
// Client  : ${company.name} (${company.logoText})
// Module  : ${mod.name} (${mod.tagline})

import React from "react";

${brandBlock(company, mod)}

const fields = ${JSON.stringify(mod.fields)};

export default function ${componentName}() {
  return (
    <main style={{ ...cssVars, minHeight: "100vh", background: "var(--brand-surface)", color: "var(--brand-on-surface)", padding: 32 }}>
      <section style={{ maxWidth: 420, margin: "0 auto", background: "white", borderRadius: 16, padding: 24 }}>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
          <BrandMark />
          <div style={{ fontSize: 11, color: "#94a3b8" }}>powered by nott</div>
        </div>
        <h1 style={{ fontSize: 24, marginTop: 20, fontWeight: 600 }}>{brand.module.name}</h1>
        <p style={{ fontSize: 12, color: "var(--brand-primary)", marginTop: 4, fontWeight: 600 }}>{brand.module.tagline}</p>
        <p style={{ fontSize: 13, color: "#64748b", marginTop: 10, lineHeight: 1.6 }}>${mod.desc}</p>
        <div style={{ marginTop: 16, display: "grid", gap: 10 }}>
          {fields.map((f) => (
            <label key={f} style={{ display: "grid", gap: 4, fontSize: 12, color: "#475569" }}>
              {f}
              <input placeholder={f} style={{ border: "1px solid #e2e8f0", borderRadius: 8, padding: "9px 11px", fontSize: 13, outlineColor: "var(--brand-primary)" }} />
            </label>
          ))}
        </div>
        <button style={{ marginTop: 16, width: "100%", background: "var(--brand-primary)", color: "var(--brand-on-primary)", border: 0, borderRadius: 10, padding: "11px 18px", fontWeight: 600, fontSize: 14, cursor: "pointer" }}>
          ${mod.cta}
        </button>
      </section>
    </main>
  );
}
`;
}

function makeSourceCode(company, mod) {
  if (mod.kind === "api") return mod.chat ? makeChatSource(company, mod) : makeApiSource(company, mod);
  if (mod.columns) return makeTableSource(company, mod);
  return makeFormSource(company, mod);
}

function makePackageJson(company, mod) {
  return JSON.stringify(
    {
      name: `${company.id}-${mod.pkg}`,
      private: true,
      version: "0.1.0",
      type: "module",
      description: `${company.name} × ${mod.name} starter (generated by nott)`,
      scripts: { dev: "vite", build: "vite build", preview: "vite preview" },
      dependencies: { react: "^18.3.1", "react-dom": "^18.3.1" },
      devDependencies: {
        "@vitejs/plugin-react": "^4.3.1",
        vite: "^5.3.0",
      },
    },
    null,
    2
  );
}

const VITE_CONFIG = `import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

// Generated by nott — a minimal, runnable React + Vite starter.
export default defineConfig({
  plugins: [react()],
});
`;

const GITIGNORE = `node_modules
dist
.DS_Store
`;

function makeReadme(company, mod) {
  const apiSection =
    mod.kind === "api"
      ? `
## Endpoint
\`${mod.endpoint}\`

## Sample payload
\`\`\`json
${JSON.stringify(mod.sample, null, 2)}
\`\`\`
${mod.chat ? "\n백엔드 연결 전에는 데모 응답(mock)으로 동작하며, 위 엔드포인트가 살아있으면 자동으로 실제 응답을 사용합니다.\n" : ""}`
      : `
## Type
UI 컴포넌트 모듈 — 백엔드 호출 없이 고객사 테마가 적용된 화면 스캐폴드입니다.
`;

  return `# ${company.id}-${mod.pkg}

> ${company.name} × ${mod.name} starter — generated by **nott**.

${mod.desc}
${apiSection}
## Run
\`\`\`bash
npm install
npm run dev
\`\`\`

## Theme
\`src/App.jsx\` 상단의 \`brand.tokens\` 값을 바꾸면 전체 테마가 CSS 변수로 재적용됩니다.

---
Generated on 2026-06-06 by nott (v7).
`;
}

// ── component ────────────────────────────────────────────────────────────────

export default function NottEasyModulesLanding() {
  const [step, setStep] = useState(1);
  const [selectedCompany, setSelectedCompany] = useState(brands[0]);
  const [selectedService, setSelectedService] = useState(modules[0]);
  const [busy, setBusy] = useState(false);

  const generatedCode = useMemo(
    () => makeSourceCode(selectedCompany, selectedService),
    [selectedCompany, selectedService]
  );

  const downloadJsx = () => {
    const blob = new Blob([generatedCode], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${selectedCompany.id}-${selectedService.pkg}.jsx`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const downloadZip = async () => {
    setBusy(true);
    try {
      const zip = new JSZip();
      const folder = `${selectedCompany.id}-${selectedService.pkg}`;
      zip.file(`${folder}/package.json`, makePackageJson(selectedCompany, selectedService));
      zip.file(`${folder}/vite.config.js`, VITE_CONFIG);
      zip.file(`${folder}/.gitignore`, GITIGNORE);
      zip.file(`${folder}/README.md`, makeReadme(selectedCompany, selectedService));
      zip.file(`${folder}/src/App.jsx`, generatedCode);
      zip.file(
        `${folder}/src/main.jsx`,
        `import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App.jsx";
ReactDOM.createRoot(document.getElementById("root")).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
`
      );
      zip.file(
        `${folder}/index.html`,
        `<!doctype html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${selectedCompany.name} × ${selectedService.name}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
`
      );

      const blob = await zip.generateAsync({ type: "blob" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${folder}-starter.zip`;
      a.click();
      URL.revokeObjectURL(url);
    } finally {
      setBusy(false);
    }
  };

  return (
    <div className="min-h-screen bg-slate-50 text-slate-900">
      <header className="mx-auto max-w-6xl px-5 py-5">
        <NottLogo height={26} />
        <div className="mt-1.5 text-xs text-slate-500">
          Easy modules for every SI project
        </div>
      </header>

      <main className="mx-auto grid max-w-6xl gap-4 px-5 pb-8 lg:grid-cols-[1fr_340px]">
        <section className="rounded-2xl border border-slate-200 bg-white p-6">
          <motion.div
            initial={{ opacity: 0, y: 8 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.3 }}
          >
            <div className="mb-3 inline-flex items-center gap-1.5 rounded-full bg-slate-100 px-2.5 py-0.5 text-xs text-slate-600">
              <Sparkles size={12} />
              Minimal SI starter
            </div>
            <h1 className="max-w-xl text-2xl font-semibold leading-snug tracking-tight md:text-3xl">
              반복 개발을 줄이고, 고객사별 모듈을 바로 만든다.
            </h1>
            <p className="mt-3 max-w-xl text-sm leading-6 text-slate-500">
              대기업 로고를 고르고, 모듈을 고르면, 해당 고객사 테마가 적용된 프리뷰와 바로 실행 가능한 starter를 생성합니다.
            </p>
          </motion.div>

          <div className="mt-6 grid gap-2 md:grid-cols-3">
            <StepCard
              active={step === 1}
              done={step > 1}
              number="01"
              title="고객사 선택"
              desc="LG / 삼성 / 현대 / 롯데 / 한화 / SK / KT / 포스코"
              onClick={() => setStep(1)}
            />
            <StepCard
              active={step === 2}
              done={step > 2}
              number="02"
              title="모듈 선택"
              desc="AI 모듈 + UI·업무 모듈"
              onClick={() => setStep(2)}
            />
            <StepCard
              active={step === 3}
              done={false}
              number="03"
              title="프리뷰 / 다운로드"
              desc="테마 화면 + 실행 가능한 starter zip"
              onClick={() => setStep(3)}
            />
          </div>

          <div className="mt-5 rounded-xl border border-slate-200 p-4">
            {step === 1 && (
              <div>
                <h2 className="text-base font-semibold">고객사를 선택하세요</h2>
                <div className="mt-3 grid gap-2 sm:grid-cols-3 md:grid-cols-4">
                  {brands.map((company) => (
                    <button
                      key={company.id}
                      onClick={() => { setSelectedCompany(company); setStep(2); }}
                      className="rounded-lg border p-3 text-left transition hover:border-slate-400"
                      style={{
                        borderColor: selectedCompany.id === company.id ? company.tokens.border  : "#e2e8f0",
                        background:  selectedCompany.id === company.id ? company.tokens.surface : "white",
                      }}
                    >
                      <div
                        className="mb-4 inline-flex h-9 w-9 items-center justify-center rounded-md text-[11px] font-bold"
                        style={{ background: company.tokens.primary, color: company.tokens.onPrimary }}
                      >
                        {company.name.slice(0, 2)}
                      </div>
                      <div className="text-sm font-semibold">{company.name}</div>
                      <div className="mt-0.5 text-[11px] font-mono text-slate-400">{company.logoText}</div>
                    </button>
                  ))}
                </div>
              </div>
            )}

            {step === 2 && (
              <div>
                <div className="flex items-end justify-between gap-3">
                  <div>
                    <h2 className="text-base font-semibold">모듈을 선택하세요</h2>
                    <p className="mt-0.5 text-xs text-slate-500">선택 고객사: {selectedCompany.name}</p>
                  </div>
                  <button onClick={() => setStep(1)} className="rounded-full bg-slate-100 px-3 py-1 text-xs hover:bg-slate-200">
                    고객사 변경
                  </button>
                </div>

                {modulesByCategory.map((cat) => (
                  <div key={cat.id} className="mt-4">
                    <div className="flex items-baseline gap-2">
                      <h3 className="text-xs font-semibold text-slate-700">{cat.name}</h3>
                      <span className="text-[11px] text-slate-400">{cat.desc}</span>
                    </div>
                    <div className="mt-2 grid gap-2 md:grid-cols-2">
                      {cat.items.map((service) => (
                        <button
                          key={service.id}
                          onClick={() => { setSelectedService(service); setStep(3); }}
                          className="rounded-lg border border-slate-200 bg-white p-4 text-left transition hover:border-slate-400"
                        >
                          <div className="flex items-center justify-between gap-2">
                            <div>
                              <div className="text-sm font-semibold">{service.name}</div>
                              <div className="text-[10px] font-mono text-slate-400">{service.tagline}</div>
                            </div>
                            <ArrowRight size={14} className="text-slate-400" />
                          </div>
                          <p className="mt-2 text-xs leading-5 text-slate-500">{service.desc}</p>
                          {service.kind === "api" ? (
                            <div className="mt-2 inline-flex items-center gap-1.5">
                              <span className="inline-block rounded bg-slate-900 px-1.5 py-0.5 font-mono text-[10px] text-slate-200">
                                {service.endpoint}
                              </span>
                              {service.chat && (
                                <span className="inline-block rounded-full border border-slate-200 px-1.5 py-0.5 text-[10px] text-slate-500">
                                  chat
                                </span>
                              )}
                            </div>
                          ) : (
                            <div className="mt-2 inline-block rounded bg-slate-100 px-1.5 py-0.5 font-mono text-[10px] text-slate-500">
                              UI 컴포넌트
                            </div>
                          )}
                        </button>
                      ))}
                    </div>
                  </div>
                ))}
              </div>
            )}

            {step === 3 && (
              <div>
                <div className="flex flex-wrap items-end justify-between gap-3">
                  <div>
                    <h2 className="text-base font-semibold">프리뷰 생성 완료</h2>
                    <p className="mt-0.5 text-xs text-slate-500">
                      {selectedCompany.name} · {selectedService.name} ·{" "}
                      <span className="font-mono text-[11px]">
                        {selectedService.endpoint ?? "UI 컴포넌트"}
                      </span>
                    </p>
                  </div>
                  <div className="flex flex-wrap gap-1.5">
                    <button onClick={() => setStep(2)} className="rounded-full bg-slate-100 px-3 py-1 text-xs hover:bg-slate-200">
                      모듈 변경
                    </button>
                    <button
                      onClick={downloadJsx}
                      className="inline-flex items-center gap-1 rounded-full border border-slate-200 bg-white px-3 py-1 text-xs font-semibold hover:border-slate-400"
                    >
                      <Download size={12} />
                      jsx
                    </button>
                    <button
                      onClick={downloadZip}
                      disabled={busy}
                      className="inline-flex items-center gap-1 rounded-full px-3 py-1 text-xs font-semibold disabled:opacity-60"
                      style={{ background: selectedCompany.tokens.primary, color: selectedCompany.tokens.onPrimary }}
                    >
                      <Package size={12} />
                      {busy ? "…" : "Starter ZIP"}
                    </button>
                  </div>
                </div>
                <div className="mt-4 grid gap-3 lg:grid-cols-2">
                  <PreviewCard company={selectedCompany} service={selectedService} />
                  <CodeCard code={generatedCode} />
                </div>
              </div>
            )}
          </div>
        </section>

        <aside className="rounded-2xl border border-slate-200 bg-slate-900 p-4 text-white">
          <div className="flex items-center gap-1.5 text-xs text-slate-300">
            <Eye size={13} />
            Live Preview
          </div>
          <div className="mt-3 overflow-hidden rounded-xl bg-white text-slate-900">
            <PreviewCard company={selectedCompany} service={selectedService} compact />
          </div>
          <div className="mt-3 rounded-xl bg-white/5 p-3">
            <div className="text-[11px] text-slate-400">Current Setup</div>
            <div className="mt-2 space-y-2">
              <InfoRow label="Company" value={selectedCompany.name} />
              <InfoRow label="Module" value={selectedService.name} />
              <InfoRow label="Type" value={selectedService.endpoint ?? "UI 컴포넌트"} mono />
              <InfoRow label="Theme" value={selectedCompany.tokens.primary} mono />
            </div>
          </div>
          <div className="mt-3 flex items-center justify-center gap-1.5 text-[10px] text-slate-500">
            <NottSymbol size={14} />
            <span>Easy modules for every SI · v8</span>
          </div>
        </aside>
      </main>
    </div>
  );
}

function StepCard({ active, done, number, title, desc, onClick }) {
  return (
    <button
      onClick={onClick}
      className={`rounded-xl border p-3 text-left transition ${
        active
          ? "border-slate-900 bg-slate-900 text-white"
          : "border-slate-200 bg-slate-50 text-slate-900 hover:border-slate-400"
      }`}
    >
      <div className="text-[10px] opacity-60">{number}</div>
      <div className="mt-3 text-sm font-semibold">{title}</div>
      <div className="mt-0.5 text-[11px] opacity-70 leading-4">{desc}</div>
      {done && <div className="mt-2 text-[10px] opacity-60">완료</div>}
    </button>
  );
}

// Brand mark: real logo SVG if the brand provides one (company.logoSvg),
// otherwise the themed text chip. Lets us drop in per-client logos later
// without touching this component.
function BrandMark({ company }) {
  const { tokens } = company;
  if (company.logoSvg) {
    return (
      <span
        className="inline-flex items-center"
        style={{ height: 22, color: tokens.primary }}
        aria-label={company.name}
        dangerouslySetInnerHTML={{ __html: company.logoSvg }}
      />
    );
  }
  const mark = company.logoText.length <= 2 ? company.logoText : company.logoText[0];
  return (
    <div className="inline-flex items-center gap-2" aria-label={company.name}>
      <span
        className="inline-flex h-6 w-6 items-center justify-center rounded-md text-[11px] font-bold tracking-tight"
        style={{ background: tokens.primary, color: tokens.onPrimary }}
      >
        {mark}
      </span>
      <span
        className="text-sm font-semibold tracking-tight"
        style={{ color: tokens.primary }}
      >
        {company.logoText}
      </span>
    </div>
  );
}

function ChatDemo({ tokens, module }) {
  const [open, setOpen] = useState(false);
  const [messages, setMessages] = useState([{ role: "assistant", text: module.greeting }]);
  const [input, setInput] = useState("");

  const send = () => {
    const text = input.trim();
    if (!text) return;
    const tag =
      module.id === "rag" ? "관련 문서를 찾아 근거와 함께 정리했습니다"
      : module.id === "slm" ? "경량 모델이 요약했습니다"
      : "사내 지식을 바탕으로 정리했습니다";
    const reply = `(${module.name} 데모) “${text}” — ${tag}. 실제 응답은 ${module.endpoint} 연결 시 제공됩니다.`;
    setMessages((m) => [...m, { role: "user", text }, { role: "assistant", text: reply }]);
    setInput("");
  };

  if (!open) {
    return (
      <button
        onClick={() => setOpen(true)}
        className="mt-4 block rounded-full px-3 py-1.5 text-xs font-semibold"
        style={{ background: tokens.primary, color: tokens.onPrimary }}
      >
        Start {module.name}
      </button>
    );
  }

  return (
    <div className="mt-3 rounded-lg border border-slate-200 bg-white">
      <div className="max-h-[180px] space-y-1.5 overflow-auto p-2">
        {messages.map((m, i) => (
          <div key={i} className={m.role === "user" ? "text-right" : "text-left"}>
            <span
              className="inline-block max-w-[85%] rounded-lg px-2 py-1 text-[11px] leading-4"
              style={
                m.role === "user"
                  ? { background: tokens.primary, color: tokens.onPrimary }
                  : { background: "#f1f5f9", color: "#0f172a" }
              }
            >
              {m.text}
            </span>
          </div>
        ))}
      </div>
      <div className="flex items-center gap-1.5 border-t border-slate-100 p-2">
        <input
          value={input}
          onChange={(e) => setInput(e.target.value)}
          onKeyDown={(e) => e.key === "Enter" && send()}
          placeholder="메시지를 입력…"
          className="flex-1 rounded-md border border-slate-200 px-2 py-1 text-[11px] outline-none"
        />
        <button
          onClick={send}
          className="inline-flex items-center gap-1 rounded-md px-2 py-1 text-[11px] font-semibold"
          style={{ background: tokens.primary, color: tokens.onPrimary }}
        >
          <Send size={11} />
          전송
        </button>
      </div>
    </div>
  );
}

function PreviewCard({ company, service, compact = false }) {
  const { tokens } = company;
  const isApi = service.kind === "api";
  return (
    <div
      className={`rounded-xl border border-slate-200 p-4 ${compact ? "min-h-[340px]" : "min-h-[320px]"}`}
      style={{ background: tokens.surface, color: tokens.onSurface }}
    >
      <div className="flex items-center justify-between">
        <BrandMark company={company} />
        <div className="rounded-full bg-white px-2 py-0.5 text-[10px] text-slate-500 border border-slate-200">
          {service.pkg}
        </div>
      </div>
      <div className="mt-8">
        <div className="text-xs font-semibold" style={{ color: tokens.primary }}>
          {company.name} Preview
        </div>
        <h3 className="mt-1.5 text-2xl font-semibold tracking-tight">
          {service.name}
        </h3>
        <p className="mt-0.5 text-xs font-semibold text-slate-500">{service.tagline}</p>
        <p className="mt-2.5 text-xs leading-5 text-slate-600">{service.desc}</p>

        {isApi ? (
          <>
            <div className="mt-3 inline-block rounded bg-slate-900 px-1.5 py-0.5 font-mono text-[10px] text-slate-100">
              {service.endpoint}
            </div>
            {service.chat ? (
              <ChatDemo tokens={tokens} module={service} />
            ) : (
              <button
                className="mt-4 block rounded-full px-3 py-1.5 text-xs font-semibold"
                style={{ background: tokens.primary, color: tokens.onPrimary }}
              >
                Start {service.name}
              </button>
            )}
          </>
        ) : service.columns ? (
          <div className="mt-3">
            <div
              className="grid gap-2 rounded-md px-2 py-1.5 text-[10px] font-semibold text-white"
              style={{ background: tokens.primary, gridTemplateColumns: `repeat(${service.columns.length}, minmax(0,1fr))` }}
            >
              {service.columns.map((c) => <span key={c}>{c}</span>)}
            </div>
            {[1, 2].map((r) => (
              <div
                key={r}
                className="grid gap-2 border-b border-slate-200 px-2 py-1.5 text-[10px] text-slate-500"
                style={{ gridTemplateColumns: `repeat(${service.columns.length}, minmax(0,1fr))` }}
              >
                {service.columns.map((c, i) => <span key={c}>{i === 0 ? `#${1000 + r}` : `${c} ${r}`}</span>)}
              </div>
            ))}
            <button
              className="mt-4 block rounded-full px-3 py-1.5 text-xs font-semibold"
              style={{ background: tokens.primary, color: tokens.onPrimary }}
            >
              {service.cta}
            </button>
          </div>
        ) : (
          <div className="mt-3 space-y-2">
            {(service.fields ?? []).map((f) => (
              <div key={f}>
                <div className="text-[10px] text-slate-500">{f}</div>
                <div className="mt-0.5 h-7 rounded-md border border-slate-200 bg-white" />
              </div>
            ))}
            <button
              className="mt-2 block w-full rounded-full px-3 py-1.5 text-xs font-semibold"
              style={{ background: tokens.primary, color: tokens.onPrimary }}
            >
              {service.cta}
            </button>
          </div>
        )}
      </div>
    </div>
  );
}

function CodeCard({ code }) {
  const copyCode = async () => {
    try { await navigator.clipboard.writeText(code); } catch (e) {}
  };
  return (
    <div className="rounded-xl border border-slate-200 bg-slate-900 p-3 text-white">
      <div className="flex items-center justify-between gap-2">
        <div className="flex items-center gap-1.5 text-xs text-slate-300">
          <Code2 size={12} />
          Generated Source
        </div>
        <button onClick={copyCode} className="rounded-full bg-white/10 px-2 py-0.5 text-[10px] hover:bg-white/20">
          Copy
        </button>
      </div>
      <pre className="mt-2 max-h-[280px] overflow-auto rounded-lg bg-black/30 p-3 text-[10px] leading-4 text-slate-300">
        {code}
      </pre>
    </div>
  );
}

function InfoRow({ label, value, mono = false }) {
  return (
    <div className="flex items-center justify-between border-b border-white/10 pb-1.5 text-xs">
      <span className="text-slate-400">{label}</span>
      <span className={`font-semibold ${mono ? "font-mono text-[10px]" : ""}`}>{value}</span>
    </div>
  );
}
