import React, { useEffect, useMemo, useState } from "react";
import JSZip from "jszip";
import { Download, Package, Code2, X, Maximize2, Smartphone, Monitor } from "lucide-react";
import { brands } from "./brand-tokens.js";
import { modules } from "./catalog.js";
import { ModuleDevice } from "./previews.jsx";

// ─────────────────────────────────────────────────────────────────────────────
// nott — Easy modules for every SI project
// Version: 2026-06-06 (v12)
//
// v11 → v12 변경점:
//  - 크게 보기 모달을 풀화면 대시보드로: PC 콘솔이 실제 풀스크린처럼 크게 렌더
//  - 모달에 미리보기 ⇄ 소스코드 슬라이드 전환 (소스는 뒤에서 슬라이드인)
//  - 슈퍼앱 모바일 목업 리뉴얼 (One ID · 배터리 · 스마트홈 on/off · 서비스 · 오늘의 일정 · 탭바)
//
// (v11) 모듈을 실제 개발 중인 6대 스마트빌딩 시스템으로 교체 (nott-infra)
//  - 폼팩터별 디바이스(PC 콘솔/모바일 폰), 브랜드 리스킨
//  - 다운로드 = 우측 목업 패널 하단 검정 영역 · nott 푸터
// ─────────────────────────────────────────────────────────────────────────────

function NottLogo({ height = 26 }) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 17 132.73 30.29" height={height} role="img" aria-label="nott">
      <rect fill="#ff595f" y="29.94" width="12.94" height="17.35" />
      <polygon fill="#ff595f" points="30.83 17 30.83 47.29 17.89 47.29 17.89 29.94 12.94 29.94 12.94 17 30.83 17" />
      <path fill="#02aa5e" d="M34.94,17v30.29h29.55v-30.29h-29.55ZM52.48,35.03h-5.54v-5.78h5.54v5.78Z" />
      <polygon fill="#ffc82b" points="99.01 17 99.01 29.94 90.33 29.94 90.33 47.29 77.4 47.29 77.4 29.94 68.72 29.94 68.72 17 99.01 17" />
      <polygon fill="#0a62bb" points="132.73 17 132.73 29.94 124.05 29.94 124.05 47.29 111.11 47.29 111.11 29.94 102.43 29.94 102.43 17 132.73 17" />
    </svg>
  );
}

function NottSymbol({ size = 18 }) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="252 0 65.04 64.29" width={size} height={size} role="img" aria-label="nott symbol">
      <rect fill="#ff595f" x="252.54" y="12.94" width="12.94" height="17.35" />
      <polygon fill="#ff595f" points="283.37 0 283.37 30.29 270.43 30.29 270.43 12.94 265.48 12.94 265.48 0 283.37 0" />
      <path fill="#02aa5e" d="M287.49,0v30.29h29.55V0h-29.55ZM305.03,18.03h-5.54v-5.78h5.54v5.78Z" />
      <polygon fill="#ffc82b" points="283.32 34 283.32 46.94 274.64 46.94 274.64 64.29 261.7 64.29 261.7 46.94 253.03 46.94 253.03 34 283.32 34" />
      <polygon fill="#0a62bb" points="317.04 34 317.04 46.94 308.36 46.94 308.36 64.29 295.42 64.29 295.42 46.94 286.74 46.94 286.74 34 317.04 34" />
    </svg>
  );
}

// ── source generation ────────────────────────────────────────────────────────

function markOf(company) {
  return company.logoText.length <= 2 ? company.logoText : company.logoText[0];
}

function brandConst(company) {
  return `const brand = ${JSON.stringify({ name: company.name, logoText: company.logoText, tokens: company.tokens })};

const cssVars = {
  "--brand-primary": brand.tokens.primary,
  "--brand-on-primary": brand.tokens.onPrimary,
  "--brand-surface": brand.tokens.surface,
  "--brand-on-surface": brand.tokens.onSurface,
};`;
}

function pascal(id) {
  return id.charAt(0).toUpperCase() + id.slice(1);
}

function makeConsoleSource(company, mod) {
  const comp = pascal(mod.id) + "Console";
  return `// Generated by nott — Easy modules for every SI project
// Package : ${mod.pkg}
// Client  : ${company.name} (${company.logoText})
// System  : ${mod.name} (${mod.tagline})
${mod.endpoint ? "// Endpoint: " + mod.endpoint + "\n" : ""}
import React from "react";

${brandConst(company)}

const MENU = ${JSON.stringify(mod.menu)};
const KPIS = ${JSON.stringify(mod.kpis)};

export default function ${comp}() {
  return (
    <div style={{ ...cssVars, display: "flex", minHeight: "100vh", fontFamily: "Inter, 'Malgun Gothic', sans-serif", background: "#f1f5f9", color: "#0f172a" }}>
      <aside style={{ width: 200, background: "#1b1b1b", color: "white", padding: 16, flexShrink: 0 }}>
        <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 18 }}>
          <span style={{ display: "inline-flex", width: 26, height: 26, alignItems: "center", justifyContent: "center", borderRadius: 7, background: "var(--brand-primary)", color: "var(--brand-on-primary)", fontWeight: 700, fontSize: 12 }}>${markOf(company)}</span>
          <span style={{ fontWeight: 700, fontSize: 13 }}>${company.logoText}</span>
        </div>
        <div style={{ fontSize: 10, textTransform: "uppercase", letterSpacing: 1, color: "rgba(255,255,255,0.4)", marginBottom: 8 }}>${mod.tagline}</div>
        {MENU.map((m, i) => (
          <div key={m} style={{ padding: "8px 10px", borderRadius: 8, fontSize: 13, marginBottom: 2, background: i === 0 ? "var(--brand-primary)" : "transparent", color: i === 0 ? "var(--brand-on-primary)" : "rgba(255,255,255,0.6)", fontWeight: i === 0 ? 600 : 400 }}>{m}</div>
        ))}
      </aside>
      <main style={{ flex: 1, minWidth: 0 }}>
        <header style={{ display: "flex", justifyContent: "space-between", alignItems: "center", background: "white", borderBottom: "1px solid #e2e8f0", padding: "14px 20px" }}>
          <div>
            <div style={{ fontWeight: 700, fontSize: 15 }}>${mod.name}</div>
            <div style={{ fontSize: 11, color: "#94a3b8" }}>${mod.desc}</div>
          </div>
          <span style={{ fontSize: 11, color: "#2E7D32", fontWeight: 600 }}>● live</span>
        </header>
        <section style={{ padding: 20 }}>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(" + KPIS.length + ", 1fr)", gap: 12 }}>
            {KPIS.map((k) => (
              <div key={k.label} style={{ background: "white", border: "1px solid #e2e8f0", borderRadius: 12, padding: 14 }}>
                <div style={{ fontSize: 11, color: "#94a3b8" }}>{k.label}</div>
                <div style={{ fontSize: 22, fontWeight: 700, color: "var(--brand-primary)", marginTop: 4 }}>{k.value}</div>
              </div>
            ))}
          </div>
          <div style={{ marginTop: 16, background: "white", border: "1px solid #e2e8f0", borderRadius: 12, padding: 48, textAlign: "center", color: "#94a3b8", fontSize: 13 }}>
            ${mod.name} 콘텐츠 영역 — nott 스타터에서 실제 화면을 구현하세요.
          </div>
        </section>
      </main>
    </div>
  );
}
`;
}

function makeAppSource(company, mod) {
  return `// Generated by nott — Easy modules for every SI project
// Package : ${mod.pkg}
// Client  : ${company.name} (${company.logoText})
// System  : ${mod.name} (${mod.tagline})

import React from "react";

${brandConst(company)}

const SMART = ${JSON.stringify(mod.extra.smart)};
const SERVICES = ${JSON.stringify(mod.extra.services)};
const TABS = ${JSON.stringify(mod.menu)};

export default function SuperApp() {
  return (
    <div style={{ ...cssVars, minHeight: "100vh", background: "var(--brand-surface)", display: "flex", justifyContent: "center", fontFamily: "Inter, 'Malgun Gothic', sans-serif", color: "#0f172a" }}>
      <div style={{ width: "100%", maxWidth: 420, background: "white", minHeight: "100vh", display: "flex", flexDirection: "column" }}>
        <div style={{ background: "var(--brand-primary)", color: "var(--brand-on-primary)", padding: "22px 18px" }}>
          <div style={{ fontSize: 16, fontWeight: 700 }}>Good morning, Mai 👋</div>
          <div style={{ fontSize: 11, opacity: 0.8 }}>Unit 1203 · Tower A · Resident</div>
        </div>
        <div style={{ flex: 1, padding: 16, display: "flex", flexDirection: "column", gap: 14 }}>
          <div style={{ background: "var(--brand-surface)", borderRadius: 14, padding: 12 }}>
            <div style={{ fontWeight: 700, fontSize: 13, marginBottom: 8 }}>스마트홈</div>
            <div style={{ display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: 8 }}>
              {SMART.map((s) => (
                <div key={s.name} style={{ background: "white", borderRadius: 10, padding: 8, textAlign: "center" }}>
                  <div style={{ fontSize: 11, fontWeight: 600 }}>{s.name}</div>
                  <div style={{ fontSize: 9, color: "var(--brand-primary)" }}>{s.state}</div>
                </div>
              ))}
            </div>
          </div>
          <div>
            <div style={{ fontWeight: 700, fontSize: 13, marginBottom: 8 }}>빠른 서비스</div>
            <div style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: 10 }}>
              {SERVICES.map((s) => (
                <div key={s} style={{ background: "var(--brand-surface)", borderRadius: 12, padding: "18px 8px", textAlign: "center", fontSize: 11, fontWeight: 600 }}>{s}</div>
              ))}
            </div>
          </div>
        </div>
        <div style={{ display: "flex", justifyContent: "space-around", borderTop: "1px solid #e2e8f0", padding: "10px 0" }}>
          {TABS.map((t, i) => (
            <div key={t} style={{ fontSize: 11, fontWeight: 600, color: i === 0 ? "var(--brand-primary)" : "#94a3b8" }}>{t}</div>
          ))}
        </div>
      </div>
    </div>
  );
}
`;
}

function makeSourceCode(company, mod) {
  return mod.form === "mobile" ? makeAppSource(company, mod) : makeConsoleSource(company, mod);
}

function makePackageJson(company, mod) {
  return JSON.stringify(
    {
      name: `${company.id}-${mod.pkg}`,
      private: true,
      version: "0.1.0",
      type: "module",
      description: `${company.name} × ${mod.name} starter (generated by nott)`,
      scripts: { dev: "vite", build: "vite build", preview: "vite preview" },
      dependencies: { react: "^18.3.1", "react-dom": "^18.3.1" },
      devDependencies: { "@vitejs/plugin-react": "^4.3.1", vite: "^5.3.0" },
    },
    null,
    2
  );
}

const VITE_CONFIG = `import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

// Generated by nott — a minimal, runnable React + Vite starter.
export default defineConfig({ plugins: [react()] });
`;

const GITIGNORE = `node_modules
dist
.DS_Store
`;

function makeReadme(company, mod) {
  return `# ${company.id}-${mod.pkg}

> ${company.name} × ${mod.name} starter — generated by **nott**.

${mod.desc}

- Form factor: ${mod.tagline}
${mod.endpoint ? "- Endpoint: `" + mod.endpoint + "`\n" : ""}
## Run
\`\`\`bash
npm install
npm run dev
\`\`\`

## Theme
\`src/App.jsx\` 상단 \`brand.tokens\` 값을 바꾸면 전체 테마가 CSS 변수로 재적용됩니다.

---
Generated on 2026-06-06 by nott (v11).
`;
}

// ── component ────────────────────────────────────────────────────────────────

export default function NottEasyModulesLanding() {
  const [selectedCompany, setSelectedCompany] = useState(brands[0]);
  const [selectedService, setSelectedService] = useState(modules[0]);
  const [busy, setBusy] = useState(false);
  const [modalOpen, setModalOpen] = useState(false);

  const generatedCode = useMemo(
    () => makeSourceCode(selectedCompany, selectedService),
    [selectedCompany, selectedService]
  );

  const downloadJsx = () => {
    const blob = new Blob([generatedCode], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${selectedCompany.id}-${selectedService.pkg}.jsx`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const downloadZip = async () => {
    setBusy(true);
    try {
      const zip = new JSZip();
      const folder = `${selectedCompany.id}-${selectedService.pkg}`;
      zip.file(`${folder}/package.json`, makePackageJson(selectedCompany, selectedService));
      zip.file(`${folder}/vite.config.js`, VITE_CONFIG);
      zip.file(`${folder}/.gitignore`, GITIGNORE);
      zip.file(`${folder}/README.md`, makeReadme(selectedCompany, selectedService));
      zip.file(`${folder}/src/App.jsx`, generatedCode);
      zip.file(
        `${folder}/src/main.jsx`,
        `import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App.jsx";
ReactDOM.createRoot(document.getElementById("root")).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
`
      );
      zip.file(
        `${folder}/index.html`,
        `<!doctype html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${selectedCompany.name} × ${selectedService.name}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
`
      );

      const blob = await zip.generateAsync({ type: "blob" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${folder}-starter.zip`;
      a.click();
      URL.revokeObjectURL(url);
    } finally {
      setBusy(false);
    }
  };

  const isMobile = selectedService.form === "mobile";

  return (
    <div className="flex min-h-screen flex-col bg-slate-50 text-slate-900">
      {/* Header */}
      <header className="sticky top-0 z-20 border-b border-slate-200 bg-white/85 shadow-sm backdrop-blur">
        <div className="mx-auto flex max-w-6xl items-center justify-between gap-3 px-5 py-3">
          <div className="flex items-center gap-3">
            <NottLogo height={24} />
            <div className="hidden h-6 w-px bg-slate-200 sm:block" />
            <div className="hidden text-[11px] font-medium leading-tight text-slate-500 sm:block">
              Easy modules<br />for every SI project
            </div>
          </div>
          <span className="inline-flex items-center gap-1.5 rounded-full bg-slate-100 px-2.5 py-1 text-[11px] font-medium text-slate-600">
            <span className="inline-block h-2 w-2 rounded-full" style={{ background: selectedCompany.tokens.primary }} />
            {selectedCompany.name} · {selectedService.name}
          </span>
        </div>
      </header>

      <main className="mx-auto w-full max-w-6xl flex-1 px-5 py-5">
        {/* Brand selector */}
        <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
          <div className="flex items-baseline justify-between">
            <h2 className="text-sm font-bold text-slate-800">고객사 선택</h2>
            <span className="text-[11px] text-slate-400">클릭하면 모든 시스템 테마가 즉시 전환됩니다</span>
          </div>
          <div className="mt-3 grid grid-cols-4 gap-2.5 sm:grid-cols-8">
            {brands.map((company) => {
              const active = selectedCompany.id === company.id;
              return (
                <button
                  key={company.id}
                  onClick={() => setSelectedCompany(company)}
                  title={company.name}
                  className="group flex flex-col items-center gap-2 rounded-xl border p-3 transition hover:-translate-y-0.5 hover:border-slate-300 hover:shadow-sm"
                  style={{ borderColor: active ? company.tokens.primary : "#e9edf2", background: active ? company.tokens.surface : "white" }}
                >
                  <span className="flex h-8 items-center justify-center">
                    {company.logo ? (
                      <img src={company.logo} alt={company.name} className="object-contain transition group-hover:scale-105" style={{ height: 22, width: "auto", maxWidth: 88 }} />
                    ) : (
                      <span className="inline-flex h-8 w-8 items-center justify-center rounded-lg text-[11px] font-bold" style={{ background: company.tokens.primary, color: company.tokens.onPrimary }}>
                        {company.name.slice(0, 2)}
                      </span>
                    )}
                  </span>
                  <span className="truncate text-[11px] font-semibold" style={{ color: active ? company.tokens.primary : "#334155" }}>{company.name}</span>
                </button>
              );
            })}
          </div>
        </section>

        <div className="mt-4 grid gap-4 lg:grid-cols-[1fr_400px]">
          {/* Module list */}
          <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
            <div className="flex items-baseline justify-between">
              <div className="flex items-center gap-2">
                <span className="h-3.5 w-1 rounded-full" style={{ background: selectedCompany.tokens.primary }} />
                <h2 className="text-base font-bold text-slate-800">스마트빌딩 인프라</h2>
                <span className="rounded-full bg-slate-100 px-1.5 py-0.5 text-[10px] font-semibold text-slate-500">{modules.length}</span>
              </div>
              <span className="text-[11px] text-slate-400">Phase 1 · 6대 시스템</span>
            </div>
            <div className="mt-3 grid gap-2.5 sm:grid-cols-2">
              {modules.map((service) => {
                const active = selectedService.id === service.id;
                return (
                  <button
                    key={service.id}
                    onClick={() => setSelectedService(service)}
                    className="group rounded-xl border p-4 text-left shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"
                    style={{ borderColor: active ? selectedCompany.tokens.primary : "#e9edf2", background: active ? selectedCompany.tokens.surface : "white" }}
                  >
                    <div className="flex items-start justify-between gap-2">
                      <div className="flex items-center gap-2">
                        <span className="rounded-md px-1.5 py-0.5 text-[10px] font-bold" style={{ background: selectedCompany.tokens.surface, color: selectedCompany.tokens.primary }}>{service.no}</span>
                        <div>
                          <div className="text-sm font-bold text-slate-800">{service.name}</div>
                          <div className="text-[10px] text-slate-400">{service.tagline}</div>
                        </div>
                      </div>
                      <span
                        className="inline-flex items-center gap-1 rounded-full px-1.5 py-0.5 text-[9px] font-semibold"
                        style={service.form === "mobile" ? { background: selectedCompany.tokens.surface, color: selectedCompany.tokens.primary } : { background: "#f1f5f9", color: "#64748b" }}
                      >
                        {service.form === "mobile" ? <Smartphone size={9} /> : <Monitor size={9} />}
                        {service.form === "mobile" ? "Mobile" : "PC"}
                      </span>
                    </div>
                    <p className="mt-2 text-xs leading-5 text-slate-500">{service.desc}</p>
                  </button>
                );
              })}
            </div>
          </section>

          {/* Right: device mockup + bottom black download area */}
          <aside className="self-start rounded-2xl border border-slate-200 bg-slate-900 p-3 text-white lg:sticky lg:top-[76px]">
            <div className="flex items-center justify-between px-1 pb-2.5 pt-1">
              <div className="flex items-center gap-1.5 text-xs text-slate-300">
                {isMobile ? <Smartphone size={13} /> : <Monitor size={13} />}
                {isMobile ? "모바일 미리보기" : "PC 미리보기"}
              </div>
              <button
                onClick={() => setModalOpen(true)}
                className="inline-flex items-center gap-1 rounded-full bg-white/10 px-2.5 py-1 text-[10px] font-semibold hover:bg-white/20"
              >
                <Maximize2 size={11} />
                크게 보기
              </button>
            </div>

            <div className="px-1">
              <ModuleDevice module={selectedService} tokens={selectedCompany.tokens} />
            </div>

            {/* bottom black area — downloads */}
            <div className="mt-3 rounded-xl bg-black/40 p-3">
              <div className="flex items-center gap-2">
                <span className="inline-flex h-6 w-6 items-center justify-center rounded-md text-[10px] font-bold" style={{ background: selectedCompany.tokens.primary, color: selectedCompany.tokens.onPrimary }}>
                  {selectedCompany.name.slice(0, 2)}
                </span>
                <div className="min-w-0">
                  <div className="truncate text-xs font-semibold">{selectedService.name}</div>
                  <div className="truncate text-[10px] text-slate-400">{selectedService.endpoint ?? selectedService.tagline} · 실행 가능한 starter</div>
                </div>
              </div>
              <div className="mt-3 flex items-center gap-2">
                <button
                  onClick={downloadJsx}
                  className="inline-flex items-center gap-1.5 rounded-lg border border-white/15 bg-white/5 px-3 py-2 text-xs font-semibold text-slate-200 transition hover:bg-white/10"
                >
                  <Download size={13} />
                  .jsx
                </button>
                <button
                  onClick={downloadZip}
                  disabled={busy}
                  className="inline-flex flex-1 items-center justify-center gap-1.5 rounded-lg px-3 py-2 text-xs font-semibold text-white shadow-sm transition hover:opacity-90 disabled:opacity-60"
                  style={{ background: selectedCompany.tokens.primary, color: selectedCompany.tokens.onPrimary }}
                >
                  <Package size={13} />
                  {busy ? "생성 중…" : "Starter ZIP 다운로드"}
                </button>
              </div>
            </div>

            <div className="mt-3 flex items-center justify-center gap-1.5 text-[10px] text-slate-500">
              <NottSymbol size={14} />
              <span>Easy modules for every SI · v12</span>
            </div>
          </aside>
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-slate-200 bg-white">
        <div className="mx-auto flex max-w-6xl flex-col items-center justify-between gap-3 px-5 py-6 sm:flex-row">
          <div className="flex items-center gap-2">
            <NottSymbol size={20} />
            <div>
              <div className="text-xs font-bold text-slate-700">nott</div>
              <div className="text-[10px] text-slate-400">Easy modules for every SI project · © 2026 UIX-SI</div>
            </div>
          </div>
          <div className="flex items-center gap-4 text-[11px] font-medium text-slate-400">
            <a href="https://nott.systems/" className="hover:text-slate-700" target="_blank" rel="noreferrer">nott.systems</a>
            <a href="https://github.com/UIX-SI/nott-systems" className="hover:text-slate-700" target="_blank" rel="noreferrer">GitHub</a>
            <span>Phase 1 · 6 Systems</span>
          </div>
        </div>
      </footer>

      {modalOpen && (
        <Modal
          company={selectedCompany}
          service={selectedService}
          code={generatedCode}
          busy={busy}
          onDownloadJsx={downloadJsx}
          onDownloadZip={downloadZip}
          onClose={() => setModalOpen(false)}
        />
      )}
    </div>
  );
}

// Full-screen preview popup — device mockup at real scale, slide to source code.
function Modal({ company, service, code, busy, onDownloadJsx, onDownloadZip, onClose }) {
  const [view, setView] = useState("preview");
  useEffect(() => {
    const onKey = (e) => e.key === "Escape" && onClose();
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [onClose]);

  const isMobile = service.form === "mobile";

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-3 sm:p-5" onClick={onClose}>
      <div className="flex h-[90vh] w-full max-w-6xl flex-col overflow-hidden rounded-2xl bg-white shadow-2xl" onClick={(e) => e.stopPropagation()}>
        {/* header */}
        <div className="flex items-center justify-between gap-3 border-b border-slate-200 px-5 py-3">
          <div className="flex min-w-0 items-center gap-2">
            <span className="inline-flex h-6 w-6 shrink-0 items-center justify-center rounded-md text-[10px] font-bold" style={{ background: company.tokens.primary, color: company.tokens.onPrimary }}>
              {company.name.slice(0, 2)}
            </span>
            <div className="min-w-0">
              <div className="flex items-center gap-1.5 truncate text-sm font-semibold">
                {service.name}
                <span className="inline-flex shrink-0 items-center gap-1 rounded-full bg-slate-100 px-1.5 py-0.5 text-[10px] font-semibold text-slate-500">
                  {isMobile ? <Smartphone size={10} /> : <Monitor size={10} />}
                  {isMobile ? "Mobile" : "PC"}
                </span>
              </div>
              <div className="truncate text-[10px] text-slate-400">{company.name} · {service.tagline}</div>
            </div>
          </div>

          {/* slide toggle: 미리보기 ⇄ 소스코드 */}
          <div className="hidden shrink-0 rounded-lg bg-slate-100 p-0.5 text-xs font-semibold sm:inline-flex">
            <button onClick={() => setView("preview")} className={`rounded-md px-3 py-1 transition ${view === "preview" ? "bg-white text-slate-800 shadow-sm" : "text-slate-500"}`}>미리보기</button>
            <button onClick={() => setView("code")} className={`rounded-md px-3 py-1 transition ${view === "code" ? "bg-white text-slate-800 shadow-sm" : "text-slate-500"}`}>&lt;/&gt; 소스</button>
          </div>

          <div className="flex shrink-0 items-center gap-1.5">
            <button onClick={onDownloadJsx} className="hidden items-center gap-1 rounded-full border border-slate-200 bg-white px-3 py-1 text-xs font-semibold hover:border-slate-400 sm:inline-flex">
              <Download size={12} />
              .jsx
            </button>
            <button
              onClick={onDownloadZip}
              disabled={busy}
              className="inline-flex items-center gap-1 rounded-full px-3 py-1 text-xs font-semibold text-white disabled:opacity-60"
              style={{ background: company.tokens.primary, color: company.tokens.onPrimary }}
            >
              <Package size={12} />
              {busy ? "…" : "ZIP"}
            </button>
            <button onClick={onClose} className="rounded-full p-1.5 text-slate-400 hover:bg-slate-100 hover:text-slate-700" aria-label="닫기">
              <X size={16} />
            </button>
          </div>
        </div>

        {/* sliding track: preview (front) ⇄ code (behind) */}
        <div className="relative flex-1 overflow-hidden bg-slate-100">
          <div
            className="flex h-full w-[200%] transition-transform duration-300 ease-out"
            style={{ transform: view === "code" ? "translateX(-50%)" : "translateX(0)" }}
          >
            <div className="flex h-full w-1/2 items-start justify-center overflow-auto p-5">
              <div className="w-full">
                <ModuleDevice module={service} tokens={company.tokens} pc={600} mobile={600} />
              </div>
            </div>
            <div className="h-full w-1/2 p-4">
              <CodeCard code={code} fill />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

function CodeCard({ code, fill = false }) {
  const copyCode = async () => {
    try { await navigator.clipboard.writeText(code); } catch (e) {}
  };
  return (
    <div className={`flex flex-col rounded-xl border border-slate-200 bg-slate-900 p-3 text-white ${fill ? "h-full" : ""}`}>
      <div className="flex items-center justify-between gap-2">
        <div className="flex items-center gap-1.5 text-xs text-slate-300">
          <Code2 size={12} />
          Generated Source · {fill ? "src/App.jsx" : "preview"}
        </div>
        <button onClick={copyCode} className="rounded-full bg-white/10 px-2 py-0.5 text-[10px] hover:bg-white/20">Copy</button>
      </div>
      <pre className={`mt-2 flex-1 overflow-auto rounded-lg bg-black/30 p-3 text-[10px] leading-4 text-slate-300 ${fill ? "" : "max-h-[480px]"}`}>{code}</pre>
    </div>
  );
}
