import React, { useMemo, useState } from "react";
import { motion } from "framer-motion";
import JSZip from "jszip";
import {
  Download,
  ArrowRight,
  Sparkles,
  Code2,
  Eye,
  Package,
} from "lucide-react";
import { brands, toCssVars } from "./brand-tokens.js";

// ─────────────────────────────────────────────────────────────────────────────
// nott — Easy modules for every SI project
// Version: 2026-06-06 (v5)
//
// v4 → v5 변경점 (테마 토큰화):
//  - 고객사 컬러/로고를 src/brand-tokens.js 로 분리 (single source of truth)
//  - 하드코딩 color/bg → 시맨틱 토큰 {primary,onPrimary,surface,onSurface,border}
//  - 생성되는 starter 코드가 CSS 변수(var(--brand-*)) 기반으로 테마 적용
//  - 새 고객사 추가 = brand-tokens.js 한 줄 추가 → 앱·생성코드 자동 반영
// ─────────────────────────────────────────────────────────────────────────────

function NottLogo({ height = 26 }) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 17 132.73 30.29"
      height={height}
      role="img"
      aria-label="nott"
    >
      <rect fill="#ff595f" y="29.94" width="12.94" height="17.35" />
      <polygon fill="#ff595f" points="30.83 17 30.83 47.29 17.89 47.29 17.89 29.94 12.94 29.94 12.94 17 30.83 17" />
      <path fill="#02aa5e" d="M34.94,17v30.29h29.55v-30.29h-29.55ZM52.48,35.03h-5.54v-5.78h5.54v5.78Z" />
      <polygon fill="#ffc82b" points="99.01 17 99.01 29.94 90.33 29.94 90.33 47.29 77.4 47.29 77.4 29.94 68.72 29.94 68.72 17 99.01 17" />
      <polygon fill="#0a62bb" points="132.73 17 132.73 29.94 124.05 29.94 124.05 47.29 111.11 47.29 111.11 29.94 102.43 29.94 102.43 17 132.73 17" />
    </svg>
  );
}

function NottSymbol({ size = 18 }) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="252 0 65.04 64.29"
      width={size}
      height={size}
      role="img"
      aria-label="nott symbol"
    >
      <rect fill="#ff595f" x="252.54" y="12.94" width="12.94" height="17.35" />
      <polygon fill="#ff595f" points="283.37 0 283.37 30.29 270.43 30.29 270.43 12.94 265.48 12.94 265.48 0 283.37 0" />
      <path fill="#02aa5e" d="M287.49,0v30.29h29.55V0h-29.55ZM305.03,18.03h-5.54v-5.78h5.54v5.78Z" />
      <polygon fill="#ffc82b" points="283.32 34 283.32 46.94 274.64 46.94 274.64 64.29 261.7 64.29 261.7 46.94 253.03 46.94 253.03 34 283.32 34" />
      <polygon fill="#0a62bb" points="317.04 34 317.04 46.94 308.36 46.94 308.36 64.29 295.42 64.29 295.42 46.94 286.74 46.94 286.74 34 317.04 34" />
    </svg>
  );
}

const services = [
  {
    id: "llm",
    pkg: "nott-llm",
    name: "nott-llm",
    tagline: "Easy LLM",
    desc: "사내 문서, 업무 데이터, 프로젝트 지식을 연결하는 기본 LLM 모듈",
    endpoint: "POST /api/llm/chat",
    sample: { messages: [{ role: "user", content: "안녕" }] },
  },
  {
    id: "slm",
    pkg: "nott-slm",
    name: "nott-slm",
    tagline: "Easy SLM",
    desc: "현장/내부망/저비용 환경에 붙이기 쉬운 경량 AI 모델 모듈",
    endpoint: "POST /api/slm/chat",
    sample: { prompt: "현장 점검 결과 요약" },
  },
  {
    id: "stt",
    pkg: "nott-stt",
    name: "nott-stt",
    tagline: "Easy STT",
    desc: "회의록, 상담, 현장 음성을 텍스트로 바꾸는 음성인식 모듈",
    endpoint: "POST /api/stt/transcribe",
    sample: { audio: "<base64>", language: "ko" },
  },
  {
    id: "rag",
    pkg: "nott-rag",
    name: "nott-rag",
    tagline: "Easy RAG",
    desc: "PDF, 문서, 매뉴얼 검색 기반 답변을 위한 RAG 모듈",
    endpoint: "POST /api/rag/query",
    sample: { query: "환불 규정", topK: 5 },
  },
  {
    id: "ocr",
    pkg: "nott-ocr",
    name: "nott-ocr",
    tagline: "Easy OCR",
    desc: "계약서, 영수증, 공문, 이미지 속 텍스트 추출 모듈",
    endpoint: "POST /api/ocr/extract",
    sample: { image: "<base64>", fields: ["date", "amount"] },
  },
  {
    id: "dashboard",
    pkg: "nott-dashboard",
    name: "nott-dashboard",
    tagline: "Easy Dashboard",
    desc: "고객사 컬러와 로고가 적용되는 운영 대시보드 모듈",
    endpoint: "GET /api/dashboard/metrics",
    sample: { range: "7d" },
  },
];

function makeSourceCode(company, service) {
  const componentName =
    service.id.charAt(0).toUpperCase() + service.id.slice(1) + "Preview";

  return `// Generated by nott — Easy modules for every SI project
// Package : ${service.pkg}
// Client  : ${company.name} (${company.logoText})
// Endpoint: ${service.endpoint}

import React from "react";

const API_ENDPOINT = "${service.endpoint}";

// Brand tokens generated from nott's brand-token system (src/brand-tokens.js).
// Theming is driven by CSS variables — swap these to re-skin for any client.
const brand = {
  name: "${company.name}",
  logoText: "${company.logoText}",
  service: { name: "${service.name}", tagline: "${service.tagline}" },
  tokens: ${JSON.stringify(company.tokens)},
};

const cssVars = {
  "--brand-primary": brand.tokens.primary,
  "--brand-on-primary": brand.tokens.onPrimary,
  "--brand-surface": brand.tokens.surface,
  "--brand-on-surface": brand.tokens.onSurface,
};

export default function ${componentName}() {
  const callApi = async () => {
    const [method, path] = API_ENDPOINT.split(" ");
    const res = await fetch(path, {
      method,
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(${JSON.stringify(service.sample)})
    });
    return res.json();
  };

  return (
    <main style={{ ...cssVars, minHeight: "100vh", background: "var(--brand-surface)", color: "var(--brand-on-surface)", padding: 32 }}>
      <section style={{ maxWidth: 880, margin: "0 auto", background: "white", borderRadius: 16, padding: 24 }}>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
          <div style={{ color: "var(--brand-primary)", fontWeight: 700, fontSize: 16 }}>{brand.logoText}</div>
          <div style={{ fontSize: 11, color: "#94a3b8" }}>powered by nott</div>
        </div>
        <h1 style={{ fontSize: 28, marginTop: 24, fontWeight: 600, letterSpacing: "-0.01em" }}>{brand.service.name}</h1>
        <p style={{ fontSize: 12, color: "var(--brand-primary)", marginTop: 4, fontWeight: 600 }}>{brand.service.tagline}</p>
        <p style={{ fontSize: 14, color: "#64748b", marginTop: 12, lineHeight: 1.6 }}>${service.desc}</p>
        <div style={{ marginTop: 16, padding: 10, background: "#0f172a", color: "#e2e8f0", borderRadius: 8, fontFamily: "monospace", fontSize: 12 }}>{API_ENDPOINT}</div>
        <button onClick={callApi} style={{ marginTop: 16, background: "var(--brand-primary)", color: "var(--brand-on-primary)", border: 0, borderRadius: 999, padding: "10px 18px", fontWeight: 600, fontSize: 13, cursor: "pointer" }}>
          Start with {brand.name}
        </button>
      </section>
    </main>
  );
}
`;
}

function makePackageJson(company, service) {
  return JSON.stringify(
    {
      name: `${company.id}-${service.pkg}`,
      private: true,
      version: "0.1.0",
      type: "module",
      description: `${company.name} × ${service.name} starter (generated by nott)`,
      scripts: { dev: "vite", build: "vite build", preview: "vite preview" },
      dependencies: { react: "^18.3.1", "react-dom": "^18.3.1" },
      devDependencies: { "@vitejs/plugin-react": "^4.3.1", vite: "^5.3.0" },
    },
    null,
    2
  );
}

function makeReadme(company, service) {
  return `# ${company.id}-${service.pkg}

> ${company.name} × ${service.name} starter — generated by **nott**.

${service.desc}

## Endpoint
\`${service.endpoint}\`

## Sample payload
\`\`\`json
${JSON.stringify(service.sample, null, 2)}
\`\`\`

## Run
\`\`\`bash
npm install
npm run dev
\`\`\`

---
Generated on 2026-06-06 by nott (v5).
`;
}

export default function NottEasyModulesLanding() {
  const [step, setStep] = useState(1);
  const [selectedCompany, setSelectedCompany] = useState(brands[0]);
  const [selectedService, setSelectedService] = useState(services[0]);
  const [busy, setBusy] = useState(false);

  const generatedCode = useMemo(
    () => makeSourceCode(selectedCompany, selectedService),
    [selectedCompany, selectedService]
  );

  const downloadJsx = () => {
    const blob = new Blob([generatedCode], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${selectedCompany.id}-${selectedService.pkg}.jsx`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const downloadZip = async () => {
    setBusy(true);
    try {
      const zip = new JSZip();
      const folder = `${selectedCompany.id}-${selectedService.pkg}`;
      zip.file(`${folder}/package.json`, makePackageJson(selectedCompany, selectedService));
      zip.file(`${folder}/README.md`, makeReadme(selectedCompany, selectedService));
      zip.file(`${folder}/src/App.jsx`, generatedCode);
      zip.file(
        `${folder}/src/main.jsx`,
        `import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App.jsx";
ReactDOM.createRoot(document.getElementById("root")).render(<App />);
`
      );
      zip.file(
        `${folder}/index.html`,
        `<!doctype html>
<html lang="ko"><head><meta charset="UTF-8" /><title>${selectedCompany.name} × ${selectedService.name}</title></head>
<body><div id="root"></div><script type="module" src="/src/main.jsx"></script></body></html>
`
      );

      const blob = await zip.generateAsync({ type: "blob" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${folder}-starter.zip`;
      a.click();
      URL.revokeObjectURL(url);
    } finally {
      setBusy(false);
    }
  };

  return (
    <div className="min-h-screen bg-slate-50 text-slate-900">
      <header className="mx-auto max-w-6xl px-5 py-5">
        <NottLogo height={26} />
        <div className="mt-1.5 text-xs text-slate-500">
          Easy modules for every SI project
        </div>
      </header>

      <main className="mx-auto grid max-w-6xl gap-4 px-5 pb-8 lg:grid-cols-[1fr_340px]">
        <section className="rounded-2xl border border-slate-200 bg-white p-6">
          <motion.div
            initial={{ opacity: 0, y: 8 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.3 }}
          >
            <div className="mb-3 inline-flex items-center gap-1.5 rounded-full bg-slate-100 px-2.5 py-0.5 text-xs text-slate-600">
              <Sparkles size={12} />
              Minimal SI starter
            </div>
            <h1 className="max-w-xl text-2xl font-semibold leading-snug tracking-tight md:text-3xl">
              반복 개발을 줄이고, 고객사별 AI 모듈을 바로 만든다.
            </h1>
            <p className="mt-3 max-w-xl text-sm leading-6 text-slate-500">
              대기업 로고를 고르고, 서비스를 고르면, 해당 고객사 테마가 적용된 프리뷰와 소스코드를 바로 생성합니다.
            </p>
          </motion.div>

          <div className="mt-6 grid gap-2 md:grid-cols-3">
            <StepCard
              active={step === 1}
              done={step > 1}
              number="01"
              title="고객사 선택"
              desc="LG / 삼성 / 현대 / 롯데 / 한화 / SK / KT / 포스코"
              onClick={() => setStep(1)}
            />
            <StepCard
              active={step === 2}
              done={step > 2}
              number="02"
              title="서비스 선택"
              desc="llm / slm / stt / rag / ocr / dashboard"
              onClick={() => setStep(2)}
            />
            <StepCard
              active={step === 3}
              done={false}
              number="03"
              title="프리뷰 / 다운로드"
              desc="테마 화면 + starter zip"
              onClick={() => setStep(3)}
            />
          </div>

          <div className="mt-5 rounded-xl border border-slate-200 p-4">
            {step === 1 && (
              <div>
                <h2 className="text-base font-semibold">고객사를 선택하세요</h2>
                <div className="mt-3 grid gap-2 sm:grid-cols-3 md:grid-cols-4">
                  {brands.map((company) => (
                    <button
                      key={company.id}
                      onClick={() => { setSelectedCompany(company); setStep(2); }}
                      className="rounded-lg border p-3 text-left transition hover:border-slate-400"
                      style={{
                        borderColor: selectedCompany.id === company.id ? company.tokens.border  : "#e2e8f0",
                        background:  selectedCompany.id === company.id ? company.tokens.surface : "white",
                      }}
                    >
                      <div
                        className="mb-4 inline-flex h-9 w-9 items-center justify-center rounded-md text-[11px] font-bold"
                        style={{ background: company.tokens.primary, color: company.tokens.onPrimary }}
                      >
                        {company.name.slice(0, 2)}
                      </div>
                      <div className="text-sm font-semibold">{company.name}</div>
                      <div className="mt-0.5 text-[11px] font-mono text-slate-400">{company.logoText}</div>
                    </button>
                  ))}
                </div>
              </div>
            )}

            {step === 2 && (
              <div>
                <div className="flex items-end justify-between gap-3">
                  <div>
                    <h2 className="text-base font-semibold">서비스를 선택하세요</h2>
                    <p className="mt-0.5 text-xs text-slate-500">선택 고객사: {selectedCompany.name}</p>
                  </div>
                  <button onClick={() => setStep(1)} className="rounded-full bg-slate-100 px-3 py-1 text-xs hover:bg-slate-200">
                    고객사 변경
                  </button>
                </div>
                <div className="mt-3 grid gap-2 md:grid-cols-2">
                  {services.map((service) => (
                    <button
                      key={service.id}
                      onClick={() => { setSelectedService(service); setStep(3); }}
                      className="rounded-lg border border-slate-200 bg-white p-4 text-left transition hover:border-slate-400"
                    >
                      <div className="flex items-center justify-between gap-2">
                        <div>
                          <div className="text-sm font-semibold">{service.name}</div>
                          <div className="text-[10px] font-mono text-slate-400">{service.tagline}</div>
                        </div>
                        <ArrowRight size={14} className="text-slate-400" />
                      </div>
                      <p className="mt-2 text-xs leading-5 text-slate-500">{service.desc}</p>
                      <div className="mt-2 inline-block rounded bg-slate-900 px-1.5 py-0.5 font-mono text-[10px] text-slate-200">
                        {service.endpoint}
                      </div>
                    </button>
                  ))}
                </div>
              </div>
            )}

            {step === 3 && (
              <div>
                <div className="flex flex-wrap items-end justify-between gap-3">
                  <div>
                    <h2 className="text-base font-semibold">프리뷰 생성 완료</h2>
                    <p className="mt-0.5 text-xs text-slate-500">
                      {selectedCompany.name} · {selectedService.name} ·{" "}
                      <span className="font-mono text-[11px]">{selectedService.endpoint}</span>
                    </p>
                  </div>
                  <div className="flex flex-wrap gap-1.5">
                    <button onClick={() => setStep(2)} className="rounded-full bg-slate-100 px-3 py-1 text-xs hover:bg-slate-200">
                      서비스 변경
                    </button>
                    <button
                      onClick={downloadJsx}
                      className="inline-flex items-center gap-1 rounded-full border border-slate-200 bg-white px-3 py-1 text-xs font-semibold hover:border-slate-400"
                    >
                      <Download size={12} />
                      jsx
                    </button>
                    <button
                      onClick={downloadZip}
                      disabled={busy}
                      className="inline-flex items-center gap-1 rounded-full px-3 py-1 text-xs font-semibold disabled:opacity-60"
                      style={{ background: selectedCompany.tokens.primary, color: selectedCompany.tokens.onPrimary }}
                    >
                      <Package size={12} />
                      {busy ? "…" : "Starter ZIP"}
                    </button>
                  </div>
                </div>
                <div className="mt-4 grid gap-3 lg:grid-cols-2">
                  <PreviewCard company={selectedCompany} service={selectedService} />
                  <CodeCard code={generatedCode} />
                </div>
              </div>
            )}
          </div>
        </section>

        <aside className="rounded-2xl border border-slate-200 bg-slate-900 p-4 text-white">
          <div className="flex items-center gap-1.5 text-xs text-slate-300">
            <Eye size={13} />
            Live Preview
          </div>
          <div className="mt-3 overflow-hidden rounded-xl bg-white text-slate-900">
            <PreviewCard company={selectedCompany} service={selectedService} compact />
          </div>
          <div className="mt-3 rounded-xl bg-white/5 p-3">
            <div className="text-[11px] text-slate-400">Current Setup</div>
            <div className="mt-2 space-y-2">
              <InfoRow label="Company" value={selectedCompany.name} />
              <InfoRow label="Service" value={selectedService.name} />
              <InfoRow label="Endpoint" value={selectedService.endpoint} mono />
              <InfoRow label="Theme" value={selectedCompany.tokens.primary} mono />
            </div>
          </div>
          <div className="mt-3 flex items-center justify-center gap-1.5 text-[10px] text-slate-500">
            <NottSymbol size={14} />
            <span>Easy AI for every SI · v5</span>
          </div>
        </aside>
      </main>
    </div>
  );
}

function StepCard({ active, done, number, title, desc, onClick }) {
  return (
    <button
      onClick={onClick}
      className={`rounded-xl border p-3 text-left transition ${
        active
          ? "border-slate-900 bg-slate-900 text-white"
          : "border-slate-200 bg-slate-50 text-slate-900 hover:border-slate-400"
      }`}
    >
      <div className="text-[10px] opacity-60">{number}</div>
      <div className="mt-3 text-sm font-semibold">{title}</div>
      <div className="mt-0.5 text-[11px] opacity-70 leading-4">{desc}</div>
      {done && <div className="mt-2 text-[10px] opacity-60">완료</div>}
    </button>
  );
}

function PreviewCard({ company, service, compact = false }) {
  const { tokens } = company;
  return (
    <div
      className={`rounded-xl border border-slate-200 p-4 ${compact ? "min-h-[340px]" : "min-h-[320px]"}`}
      style={{ background: tokens.surface, color: tokens.onSurface }}
    >
      <div className="flex items-center justify-between">
        <div
          className="rounded-md px-3 py-1.5 text-xs font-bold"
          style={{ background: tokens.primary, color: tokens.onPrimary }}
        >
          {company.logoText}
        </div>
        <div className="rounded-full bg-white px-2 py-0.5 text-[10px] text-slate-500 border border-slate-200">
          {service.pkg}
        </div>
      </div>
      <div className="mt-8">
        <div className="text-xs font-semibold" style={{ color: tokens.primary }}>
          {company.name} Preview
        </div>
        <h3 className="mt-1.5 text-2xl font-semibold tracking-tight">
          {service.name}
        </h3>
        <p className="mt-0.5 text-xs font-semibold text-slate-500">{service.tagline}</p>
        <p className="mt-2.5 text-xs leading-5 text-slate-600">{service.desc}</p>
        <div className="mt-3 inline-block rounded bg-slate-900 px-1.5 py-0.5 font-mono text-[10px] text-slate-100">
          {service.endpoint}
        </div>
        <button
          className="mt-4 block rounded-full px-3 py-1.5 text-xs font-semibold"
          style={{ background: tokens.primary, color: tokens.onPrimary }}
        >
          Start {service.name}
        </button>
      </div>
      <div className="mt-6 grid grid-cols-3 gap-2">
        {["API", "UI", "CODE"].map((item) => (
          <div key={item} className="rounded-md bg-white p-2 text-center text-[11px] font-semibold border border-slate-200">
            {item}
          </div>
        ))}
      </div>
    </div>
  );
}

function CodeCard({ code }) {
  const copyCode = async () => {
    try { await navigator.clipboard.writeText(code); } catch (e) {}
  };
  return (
    <div className="rounded-xl border border-slate-200 bg-slate-900 p-3 text-white">
      <div className="flex items-center justify-between gap-2">
        <div className="flex items-center gap-1.5 text-xs text-slate-300">
          <Code2 size={12} />
          Generated Source
        </div>
        <button onClick={copyCode} className="rounded-full bg-white/10 px-2 py-0.5 text-[10px] hover:bg-white/20">
          Copy
        </button>
      </div>
      <pre className="mt-2 max-h-[280px] overflow-auto rounded-lg bg-black/30 p-3 text-[10px] leading-4 text-slate-300">
        {code}
      </pre>
    </div>
  );
}

function InfoRow({ label, value, mono = false }) {
  return (
    <div className="flex items-center justify-between border-b border-white/10 pb-1.5 text-xs">
      <span className="text-slate-400">{label}</span>
      <span className={`font-semibold ${mono ? "font-mono text-[10px]" : ""}`}>{value}</span>
    </div>
  );
}
